title: Massimo Tisi
author: Massimo Tisi
email: firstname.lastname@mines-nantes.fr
description: > # this means to ignore newlines until "baseurl:"
  My minimalistic academic page, pointing to my publications, 
  teaching material and organized events. 
baseurl: ""
twitter_username: massimotisi
github_username:  massimotisi

profile_picture: profile.jpeg

institute_name: AtlanMod team (Inria, Mines Nantes, LS2N)
institute_logo: logo.png
institute_url: http://www.emn.fr/z-info/atlanmod

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
