title: Massimo Tisi
author: Massimo Tisi
email: firstname.lastname@imt-atlantique.fr
description: > # this means to ignore newlines until "baseurl:"
  My minimalistic academic page, pointing to my publications, 
  teaching material and organized events. 
baseurl: ""
twitter_username: massimotisi
github_username:  massimotisi

profile_picture: profile.jpeg

institute_name: IMT Atlantique, LS2N - CNRS
institute_logo: logo.png
institute_url: https://naomod.github.io/

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-88048106-1